name: test em

on:
  push:
    branches: [ develop, release ]
  pull_request:
    branches: [ develop, release ]
  workflow_dispatch:

jobs:
 test-em:
    runs-on: ubuntu-latest
    name: Test EM
    strategy:
      matrix:
        php: ["PHP-8.0", "PHP-8.1", "PHP-8.2", "PHP-8.3", "PHP-8.4", "master"]
    steps:
      - name: Checkout em
        uses: actions/checkout@v4
        
      - name: Checkout php-src (${{ matrix.php }})
        uses: actions/checkout@v4
        with:
          repository: php/php-src
          ref: ${{ matrix.php }}
          path: php-src

      - name: Build em (${{ matrix.php }})
        uses: ./
        with:
          EM_PHP_DIR: ./php-src
          with: >
            ctype zlib bz2 sqlite3 pdo pdo-sqlite
            phar mbstring calendar bcmath opcache

      - name: Test em (${{ matrix.php }})
        run: |
          ./php-em-test.js tests --verbose

      - name: Upload Artifacts (${{ matrix.php }})
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.php }}-em
          path: |
            php-em.js
            php-em.wasm
